version: '3.8'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Adjust this port as needed for your setup
    volumes:
      - .:/app            # Mount the project directory for live reloading
      - node_modules:/app/node_modules # Use an anonymous volume to prevent overwriting node_modules
    working_dir: /app 
    environment:
      - NODE_ENV=development
    command: npm run dev  # Start the Vue 3 development server

volumes:
  node_modules: